server {
    listen 80;
    server_name garage.arturoduran.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name garage.arturoduran.dev;

    ssl_certificate     /etc/letsencrypt/archive/garage.arturoduran.dev/fullchain1.pem;
    ssl_certificate_key /etc/letsencrypt/archive/garage.arturoduran.dev/privkey1.pem;

    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/ {
        alias /usr/share/nginx/html/.well-known/;
        add_header Content-Type text/plain;
    }

    location /api/ {
        proxy_pass http://backend:3001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}